/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    IconCommunity: (typeof import('./components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./components/icons/IconTooling.vue'))['default']
    Logo: typeof import('./components/shared/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: (typeof import('./components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./components/WelcomeItem.vue'))['default']
  }
}
